"""empty message

Revision ID: 664d1121e30a
Revises: 7a5a98f93f92
Create Date: 2021-08-02 18:17:30.845708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664d1121e30a'
down_revision = '7a5a98f93f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumno', 'apellido',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumno', 'apellido',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
